apiVersion: v1
kind: Namespace
metadata:
  name: flask-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: flask-app
data:
  FLASK_MESSAGE: "Hello from ConfigMap!"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/flask-app:PLACEHOLDER
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: FLASK_MESSAGE
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-app
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
