apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: flask-app
  namespace: flux-system
spec:
  interval: 1m
  image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/flask-app
