name: Pull public and Push to ECR

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    environment: int
    permissions:
      id-token: write
      contents: read
    env:
      AWS_ECR: 796618404628.dkr.ecr.eu-central-1.amazonaws.com
      PUBLIC_REPOSITORY_NAME: bitnami/kubectl
      IMAGE_TAG: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GIT_ROLE_ARN }}
          aws-region: eu-central-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract version
        run: |
          VERSION=${GITHUB_REF##*/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin ${AWS_ECR}
          docker pull ${PUBLIC_REPOSITORY_NAME}:${IMAGE_TAG}
          docker tag  ${PUBLIC_REPOSITORY_NAME}:${IMAGE_TAG} ${AWS_ECR}/${PUBLIC_REPOSITORY_NAME}:${IMAGE_TAG}
          docker push ${AWS_ECR}/${PUBLIC_REPOSITORY_NAME}:${IMAGE_TAG}
          