apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-flask
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-flask
  template:
    metadata:
      labels:
        app: demo-flask
    spec:
      serviceAccountName: ecr-credentials-sync
      containers:
        - name: flask
          image: 796618404628.dkr.ecr.eu-central-1.amazonaws.com/flask-app-int:1.0.0 # {"$imagepolicy": "flux-system:flask-app"}
          ports:
            - containerPort: 5000
          env:
          - name: FLASK_MESSAGE
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: FLASK_MESSAGE
