apiVersion: v1
kind: Service
metadata:
  name: demo-flask
  namespace: demo
spec:
  type: LoadBalancer
  selector:
    app: demo-flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
