apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: flask-app
  namespace: flux-system
spec:
  secretRef:
    name: ecr-credentials
  image: 796618404628.dkr.ecr.eu-central-1.amazonaws.com/flask-repo-int
  interval: 1m0s