apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-app
  namespace: flux-system
spec:
  interval: 2m
  path: "./project/clusters/demo"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
# after you used flux bootstrap github, with one important clarification:
# When you bootstrap Flux using flux bootstrap github, 
# Flux automatically creates a GitRepository resource in the flux-system namespace. 
# By default:
# Name: flux-system
# Namespace: flux-system